---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: terraform-gcp-iam
  description: TF Component for creating IAM in Google Cloud Platform
  annotations:
    github.com/project-slug: honestbank/terraform-gcp-iam
    github.com/team-slug: honestbank/devops-engineers
spec:
  type: tf-component
  lifecycle: production
  owner: group:devops-engineers
  system: infrastructure
