name: terratest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  TERRATEST_GOOGLE_CREDENTIALS: ${{ secrets.TERRATEST_GOOGLE_CREDENTIALS }}
  GOOGLE_PROJECT: ${{ secrets.TERRATEST_GOOGLE_PROJECT }}
  GCP_SA_EMAIL: ${{ secrets.TERRATEST_GCP_SA_EMAIL }}
  TF_VAR_google_credentials: ${{ secrets.TERRATEST_GOOGLE_CREDENTIALS }}
  TF_VAR_shared_vpc_host_google_credentials: ${{ secrets.TERRATEST_GOOGLE_CREDENTIALS }}
jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go (1.18)
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      - name: 'Log in to Google Cloud (auth)'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.TERRATEST_GOOGLE_CREDENTIALS }}'
      - name: 'Set up Google Cloud SDK (setup-gcloud)'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Set Google Cloud project
        run: gcloud config set project $GOOGLE_PROJECT
      - name: Run terratest
        run: |
          cd test
          go test -v -timeout 5m
      - name: Release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.3
            @semantic-release/changelog@6.0.1
